const UIassets = [
    // Main menu
    "./Imagery/UI/Game start.gif",
    "./Imagery/UI/Opening menu image.png",
    // Stats
    "./Imagery/UI/Stats blade.png",
    "./Imagery/UI/Red orb.png",
    // Hotbar srcs
    "./Imagery/UI/Arm of Sparta.png",
    "./Imagery/UI/Claws of Hades.png",
    "./Imagery/UI/Nemean cestus.png",
    "./Imagery/UI/Blade of Olympus.png",
    // Sparta
    "./Imagery/UI/Sparta.png",
    "./Imagery/UI/Kratos standing animation.gif",
    "./Imagery/UI/Kratos standing animation (Nemesis whip).gif",
    "./Imagery/UI/Kratos standing animation (Arms of Sparta).gif",
    "./Imagery/UI/Kratos standing animation (Claws of Hades).gif",
    "./Imagery/UI/Kratos standing animation (Gauntlet of Zeus).gif",
    "./Imagery/UI/Kratos standing animation (Nemean cestus).gif",
    "./Imagery/UI/Kratos standing animation (Blade of Olympus).gif",
    "./Imagery/UI/Sparta smithy.png",
    "./Imagery/UI/Athens.png",
    "./Imagery/UI/Underworld.png",
    "./Imagery/UI/Mount Olympus.png",
    // Smithy
    "./Imagery/UI/In smithy.png",
    "./Imagery/UI/Arms of Sparta.png",
    "./Imagery/UI/Arms of Sparta (outlined).png",
    "./Imagery/UI/Nemesis whip.png",
    "./Imagery/UI/Nemesis whip (outlined).png",
    "./Imagery/UI/Gauntlet of Zeus.png",
    "./Imagery/UI/Gauntlet of Zeus (outlined).png",
    // Athens
    "./Imagery/UI/At Athens.png",
    "./Imagery/UI/Undead archer.png",
    "./Imagery/UI/Undead legionnaire.png",
    "./Imagery/UI/Cursed legionnaire.png",
    "./Imagery/UI/Banshee.png",
    "./Imagery/UI/Fallen legionnaire.png",
    "./Imagery/UI/Banshee.png",
    "./Imagery/UI/Gorgon.png",
    "./Imagery/UI/Medusa.png",
    // Underworld
    "./Imagery/UI/In underworld.png",
    "./Imagery/UI/Hoplite.png",
    "./Imagery/UI/Satyr.png",
    "./Imagery/UI/Minotaur.png",
    "./Imagery/UI/Cyclops.png",
    "./Imagery/UI/Hades.png",
    // Olympus
    "./Imagery/UI/At Olympus.png",
    "./Imagery/UI/Hermes.png",
    "./Imagery/UI/Hercules.png",
    "./Imagery/UI/Zeus.png"
];

const battleAssets = [
    // --- Kratos ---
    "Imagery/battle/Kratos standing right.png",
    "Imagery/battle/Kratos standing left.png",
    "Imagery/battle/Kratos jogging right.png",
    "Imagery/battle/Kratos jogging left.png",
    "Imagery/battle/Kratos jumps right.png",
    "Imagery/battle/Kratos jumps left.png",
    "Imagery/battle/Kratos falls right.png",
    "Imagery/battle/Kratos falls left.png",
    "Imagery/battle/Kratos dodging right.png",
    "Imagery/battle/Kratos dodging left.png",
    "Imagery/battle/Kratos damage right.png",
    "Imagery/battle/Kratos damage left.png",
    "Imagery/battle/Kratos air damage right.png",
    "Imagery/battle/Kratos air damage left.png",
    "Imagery/battle/Kratos covering ears right.png",
    "Imagery/battle/Kratos covering ears left.png",
    "Imagery/battle/Kratos petrified right.png",
    "Imagery/battle/Kratos petrified left.png",
    "Imagery/battle/Kratos soul right.png",
    "Imagery/battle/Kratos soul left.png",
    "Imagery/battle/Kratos held by hands right.png",
    "Imagery/battle/Kratos held by hands left.png",
    "Imagery/battle/Kratos dead right.png",
    "Imagery/battle/Kratos dead left.png",
    "Imagery/battle/Kratos dead as stone right.png",
    "Imagery/battle/Kratos dead as stone left.png",
    "Imagery/battle/Kratos fighting stance right (Blades of chaos).png",
    "Imagery/battle/Kratos fighting stance left (Blades of chaos).png",
    "Imagery/battle/Kratos fighting stance right (Blades of chaos)-lit.png",
    "Imagery/battle/Kratos fighting stance left (Blades of chaos)-lit.png",
    "Imagery/battle/Kratos light attacks right with blades of chaos 1.png",
    "Imagery/battle/Kratos light attacks right with blades of chaos 2.png",
    "Imagery/battle/Kratos light attacks right with blades of chaos 3.png",
    "Imagery/battle/Kratos light attacks left with blades of chaos 1.png",
    "Imagery/battle/Kratos light attacks left with blades of chaos 2.png",
    "Imagery/battle/Kratos light attacks left with blades of chaos 3.png",
    "Imagery/battle/Kratos heavy attacks right with blades of chaos 1.png",
    "Imagery/battle/Kratos heavy attacks right with blades of chaos 2.png",
    "Imagery/battle/Kratos heavy attacks left with blades of chaos 1.png",
    "Imagery/battle/Kratos heavy attacks left with blades of chaos 2.png",
    "Imagery/battle/Kratos blocking right with blades of chaos.png",
    "Imagery/battle/Kratos blocking left with blades of chaos.png",
    "Imagery/battle/Kratos aerial attack right with blades of chaos.png",
    "Imagery/battle/Kratos aerial attack left with blades of chaos.png",
    "Imagery/battle/Kratos fighting stance right (Nemesis whip).png",
    "Imagery/battle/Kratos fighting stance left (Nemesis whip).png",
    "Imagery/battle/Kratos fighting stance right (Nemesis whip)-lit.png",
    "Imagery/battle/Kratos fighting stance left (Nemesis whip)-lit.png",
    "Imagery/battle/Kratos light attacks right with nemesis whip 1.png",
    "Imagery/battle/Kratos light attacks right with nemesis whip 2.png",
    "Imagery/battle/Kratos light attacks right with nemesis whip 3.png",
    "Imagery/battle/Kratos light attacks left with nemesis whip 1.png",
    "Imagery/battle/Kratos light attacks left with nemesis whip 2.png",
    "Imagery/battle/Kratos light attacks left with nemesis whip 3.png",
    "Imagery/battle/Kratos heavy attacks right with nemesis whip 1.png",
    "Imagery/battle/Kratos heavy attacks right with nemesis whip 2.png",
    "Imagery/battle/Kratos heavy attacks left with nemesis whip 1.png",
    "Imagery/battle/Kratos heavy attacks left with nemesis whip 2.png",
    "Imagery/battle/Kratos blocking right with nemesis whip.png",
    "Imagery/battle/Kratos blocking left with nemesis whip.png",
    "Imagery/battle/Kratos aerial attack right with nemesis whip.png",
    "Imagery/battle/Kratos aerial attack left with nemesis whip.png",
    "Imagery/battle/Kratos fighting stance right (Arms of Sparta).png",
    "Imagery/battle/Kratos fighting stance left (Arms of Sparta).png",
    "Imagery/battle/Kratos fighting stance right (Arms of Sparta)-lit.png",
    "Imagery/battle/Kratos fighting stance left (Arms of Sparta)-lit.png",
    "Imagery/battle/Kratos light attacks right with arms of sparta 1.png",
    "Imagery/battle/Kratos light attacks right with arms of sparta 2.png",
    "Imagery/battle/Kratos light attacks left with arms of sparta 1.png",
    "Imagery/battle/Kratos light attacks left with arms of sparta 2.png",
    "Imagery/battle/Kratos heavy attacks right with arms of sparta 1.png",
    "Imagery/battle/Kratos heavy attacks right with arms of sparta 2.png",
    "Imagery/battle/Kratos heavy attacks left with arms of sparta 1.png",
    "Imagery/battle/Kratos heavy attacks left with arms of sparta 2.png",
    "Imagery/battle/Kratos blocking right with arms of sparta.png",
    "Imagery/battle/Kratos blocking left with arms of sparta.png",
    "Imagery/battle/Kratos aerial attack right with arms of sparta.png",
    "Imagery/battle/Kratos aerial attack left with arms of sparta.png",
    "Imagery/battle/Kratos fighting stance right (Claws of Hades).png",
    "Imagery/battle/Kratos fighting stance left (Claws of Hades).png",
    "Imagery/battle/Kratos fighting stance right (Claws of Hades)-lit.png",
    "Imagery/battle/Kratos fighting stance left (Claws of Hades)-lit.png",
    "Imagery/battle/Kratos light attacks right with claws of hades 1.png",
    "Imagery/battle/Kratos light attacks right with claws of hades 2.png",
    "Imagery/battle/Kratos light attacks right with claws of hades 3.png",
    "Imagery/battle/Kratos light attacks left with claws of hades 1.png",
    "Imagery/battle/Kratos light attacks left with claws of hades 2.png",
    "Imagery/battle/Kratos light attacks left with claws of hades 3.png",
    "Imagery/battle/Kratos heavy attacks right with claws of hades 1.png",
    "Imagery/battle/Kratos heavy attacks right with claws of hades 2.png",
    "Imagery/battle/Kratos heavy attacks left with claws of hades 1.png",
    "Imagery/battle/Kratos heavy attacks left with claws of hades 2.png",
    "Imagery/battle/Kratos blocking right with claws of hades.png",
    "Imagery/battle/Kratos blocking left with claws of hades.png",
    "Imagery/battle/Kratos aerial attack right with claws of hades.png",
    "Imagery/battle/Kratos aerial attack left with claws of hades.png",
    "Imagery/battle/Kratos fighting stance right (Gauntlet of Zeus).png",
    "Imagery/battle/Kratos fighting stance left (Gauntlet of Zeus).png",
    "Imagery/battle/Kratos light attacks right with gauntlet of zeus 1.png",
    "Imagery/battle/Kratos light attacks right with gauntlet of zeus 2.png",
    "Imagery/battle/Kratos light attacks left with gauntlet of zeus 1.png",
    "Imagery/battle/Kratos light attacks left with gauntlet of zeus 2.png",
    "Imagery/battle/Kratos heavy attacks right with gauntlet of zeus 1.png",
    "Imagery/battle/Kratos heavy attacks right with gauntlet of zeus 2.png",
    "Imagery/battle/Kratos heavy attacks left with gauntlet of zeus 1.png",
    "Imagery/battle/Kratos heavy attacks left with gauntlet of zeus 2.png",
    "Imagery/battle/Kratos blocking right with gauntlet of zeus.png",
    "Imagery/battle/Kratos blocking left with gauntlet of zeus.png",
    "Imagery/battle/Kratos aerial attack right with gauntlet of zeus.png",
    "Imagery/battle/Kratos aerial attack left with gauntlet of zeus.png",
    "Imagery/battle/Kratos fighting stance right (Nemean cestus).png",
    "Imagery/battle/Kratos fighting stance left (Nemean cestus).png",
    "Imagery/battle/Kratos light attacks right with nemean cestus 1.png",
    "Imagery/battle/Kratos light attacks right with nemean cestus 2.png",
    "Imagery/battle/Kratos light attacks left with nemean cestus 1.png",
    "Imagery/battle/Kratos light attacks left with nemean cestus 2.png",
    "Imagery/battle/Kratos heavy attacks right with nemean cestus 1.png",
    "Imagery/battle/Kratos heavy attacks right with nemean cestus 2.png",
    "Imagery/battle/Kratos heavy attacks left with nemean cestus 1.png",
    "Imagery/battle/Kratos heavy attacks left with nemean cestus 2.png",
    "Imagery/battle/Kratos blocking right with nemean cestus.png",
    "Imagery/battle/Kratos blocking left with nemean cestus.png",
    "Imagery/battle/Kratos aerial attack right with nemean cestus.png",
    "Imagery/battle/Kratos aerial attack left with nemean cestus.png",
    "Imagery/battle/Kratos fighting stance right (Blade of Olympus).png",
    "Imagery/battle/Kratos fighting stance left (Blade of Olympus).png",
    "Imagery/battle/Kratos fighting stance right (Blade of Olympus)-lit.png",
    "Imagery/battle/Kratos fighting stance left (Blade of Olympus)-lit.png",
    "Imagery/battle/Kratos light attacks right with blade of olympus 1.png",
    "Imagery/battle/Kratos light attacks right with blade of olympus 2.png",
    "Imagery/battle/Kratos light attacks left with blade of olympus 1.png",
    "Imagery/battle/Kratos light attacks left with blade of olympus 2.png",
    "Imagery/battle/Kratos heavy attacks right with blade of olympus 1.png",
    "Imagery/battle/Kratos heavy attacks right with blade of olympus 2.png",
    "Imagery/battle/Kratos heavy attacks left with blade of olympus 1.png",
    "Imagery/battle/Kratos heavy attacks left with blade of olympus 2.png",
    "Imagery/battle/Kratos blocking right with blade of olympus.png",
    "Imagery/battle/Kratos blocking left with blade of olympus.png",
    "Imagery/battle/Kratos aerial attack right with blade of olympus.png",
    "Imagery/battle/Kratos aerial attack left with blade of olympus.png",
    // --- Death screen image ---
    "Imagery/battle/You are dead GoW CoO.png",
    // ---- Athens ----
    // Backgrounds
    "Imagery/battle/Aegean sea battle 1.png",
    "Imagery/battle/Aegean sea battle 2.png",
    "Imagery/battle/Aegean sea battle 3.png",
    "Imagery/battle/Athens docks 1.png",
    "Imagery/battle/Athens docks 2.png",
    "Imagery/battle/Athens legionnaires battle.png",
    "Imagery/battle/Athens after docks.png",
    "Imagery/battle/Gates of Athens.png",
    "Imagery/battle/Medusa battle area.png",
    "Imagery/battle/Athens battle area.png", // for freeplay
    // Enemies
    "Imagery/battle/Undead Archer facing left.png",
    "Imagery/battle/Undead Archer facing right.png",
    "Imagery/battle/Undead Archer shoots right.png",
    "Imagery/battle/Undead Archer shoots left.png",
    "Imagery/battle/Arrow left.png",
    "Imagery/battle/Arrow right.png",
    "Imagery/battle/Undead Archer light attacks left.png",
    "Imagery/battle/Undead Archer light attacks right.png",
    "Imagery/battle/Undead Archer dead left.png",
    "Imagery/battle/Undead Archer dead right.png",
    "Imagery/battle/Undead Legionnaire facing left.png",
    "Imagery/battle/Undead Legionnaire facing right.png",
    "Imagery/battle/Undead Legionnaire chasing left.png",
    "Imagery/battle/Undead Legionnaire chasing right.png",
    "Imagery/battle/Undead Legionnaire light attacks left.png",
    "Imagery/battle/Undead Legionnaire light attacks right.png",
    "Imagery/battle/Undead Legionnaire heavy attacks left.png",
    "Imagery/battle/Undead Legionnaire heavy attacks right.png",
    "Imagery/battle/Undead Legionnaire dead left.png",
    "Imagery/battle/Undead Legionnaire dead right.png",
    "Imagery/battle/Cursed Legionnaire facing left.png",
    "Imagery/battle/Cursed Legionnaire facing right.png",
    "Imagery/battle/Cursed Legionnaire chasing left.png",
    "Imagery/battle/Cursed Legionnaire chasing right.png",
    "Imagery/battle/Cursed Legionnaire light attacks left.png",
    "Imagery/battle/Cursed Legionnaire light attacks right.png",
    "Imagery/battle/Cursed Legionnaire heavy attacks left.png",
    "Imagery/battle/Cursed Legionnaire heavy attacks right.png",
    "Imagery/battle/Cursed Legionnaire leaps left.png",
    "Imagery/battle/Cursed Legionnaire leaps right.png",
    "Imagery/battle/Cursed Legionnaire leap attacks left.png",
    "Imagery/battle/Cursed Legionnaire leap attacks right.png",
    "Imagery/battle/Cursed Legionnaire lands left.png",
    "Imagery/battle/Cursed Legionnaire lands right.png",
    "Imagery/battle/Cursed Legionnaire dead left.png",
    "Imagery/battle/Cursed Legionnaire dead right.png",
    "Imagery/battle/Banshee facing left.png",
    "Imagery/battle/Banshee facing right.png",
    "Imagery/battle/Banshee chasing left.png",
    "Imagery/battle/Banshee chasing right.png",
    "Imagery/battle/Banshee light attacks left.png",
    "Imagery/battle/Banshee light attacks right.png",
    "Imagery/battle/Banshee heavy attacks left.png",
    "Imagery/battle/Banshee heavy attacks right.png",
    "Imagery/battle/Banshee screams left.png",
    "Imagery/battle/Banshee screams right.png",
    "Imagery/battle/Banshee dead left.png",
    "Imagery/battle/Banshee dead right.png",
    "Imagery/battle/Fallen Legionnaire facing left.png",
    "Imagery/battle/Fallen Legionnaire facing right.png",
    "Imagery/battle/Fallen Legionnaire chasing left.png",
    "Imagery/battle/Fallen Legionnaire chasing right.png",
    "Imagery/battle/Fallen Legionnaire light attacks left.png",
    "Imagery/battle/Fallen Legionnaire light attacks right.png",
    "Imagery/battle/Fallen Legionnaire heavy attacks left.png",
    "Imagery/battle/Fallen Legionnaire heavy attacks right.png",
    "Imagery/battle/Fallen Legionnaire blocks left.png",
    "Imagery/battle/Fallen Legionnaire blocks right.png",
    "Imagery/battle/Fallen Legionnaire leaps left.png",
    "Imagery/battle/Fallen Legionnaire leaps right.png",
    "Imagery/battle/Fallen Legionnaire leap attacks left.png",
    "Imagery/battle/Fallen Legionnaire leap attacks right.png",
    "Imagery/battle/Fallen Legionnaire lands left.png",
    "Imagery/battle/Fallen Legionnaire lands right.png",
    "Imagery/battle/Fallen Legionnaire dead left.png",
    "Imagery/battle/Fallen Legionnaire dead right.png",
    "Imagery/battle/Gorgon facing left.png",
    "Imagery/battle/Gorgon facing right.png",
    "Imagery/battle/Gorgon chasing left.png",
    "Imagery/battle/Gorgon chasing right.png",
    "Imagery/battle/Gorgon light attacks left.png",
    "Imagery/battle/Gorgon light attacks right.png",
    "Imagery/battle/Gorgon heavy attacks left.png",
    "Imagery/battle/Gorgon heavy attacks right.png",
    "Imagery/battle/Gorgon petrifies left.png",
    "Imagery/battle/Gorgon petrifies right.png",
    "Imagery/battle/Gorgon dead left.png",
    "Imagery/battle/Gorgon dead right.png",
    "Imagery/battle/Medusa facing left.png",
    "Imagery/battle/Medusa facing right.png",
    "Imagery/battle/Medusa chasing left.png",
    "Imagery/battle/Medusa chasing right.png",
    "Imagery/battle/Medusa light attacks left.png",
    "Imagery/battle/Medusa light attacks right.png",
    "Imagery/battle/Medusa heavy attacks left.png",
    "Imagery/battle/Medusa heavy attacks right.png",
    "Imagery/battle/Medusa petrifies left.png",
    "Imagery/battle/Medusa petrifies right.png",
    "Imagery/battle/Medusa dead left.png",
    "Imagery/battle/Medusa dead right.png",
    // --- Underworld ---
    // Backgrounds
    "Imagery/battle/Underworld entrance.png",
    "Imagery/battle/Underworld after entrance.png",
    "Imagery/battle/Underworld scorched passage.png",
    "Imagery/battle/Underworld ashen keep.png",
    "Imagery/battle/Hades battle area.png",
    "Imagery/battle/Underworld battle area.png", // for freeplay
    // Enemies
    "Imagery/battle/Hoplite facing left.png",
    "Imagery/battle/Hoplite facing right.png",
    "Imagery/battle/Hoplite chasing left.png",
    "Imagery/battle/Hoplite chasing right.png",
    "Imagery/battle/Hoplite light attacks left.png",
    "Imagery/battle/Hoplite light attacks right.png",
    "Imagery/battle/Hoplite heavy attacks left.png",
    "Imagery/battle/Hoplite heavy attacks right.png",
    "Imagery/battle/Hoplite blocks left.png",
    "Imagery/battle/Hoplite blocks right.png",
    "Imagery/battle/Hoplite dead left.png",
    "Imagery/battle/Hoplite dead right.png",
    "Imagery/battle/Satyr facing left.png",
    "Imagery/battle/Satyr facing right.png",
    "Imagery/battle/Satyr chasing left.png",
    "Imagery/battle/Satyr chasing right.png",
    "Imagery/battle/Satyr light attacks left.png",
    "Imagery/battle/Satyr light attacks right.png",
    "Imagery/battle/Satyr heavy attacks left.png",
    "Imagery/battle/Satyr heavy attacks right.png",
    "Imagery/battle/Satyr blocks left.png",
    "Imagery/battle/Satyr blocks right.png",
    "Imagery/battle/Satyr dead left.png",
    "Imagery/battle/Satyr dead right.png",
    "Imagery/battle/Minotaur facing left.png",
    "Imagery/battle/Minotaur facing right.png",
    "Imagery/battle/Minotaur chasing left.png",
    "Imagery/battle/Minotaur chasing right.png",
    "Imagery/battle/Minotaur light attacks left.png",
    "Imagery/battle/Minotaur light attacks right.png",
    "Imagery/battle/Minotaur heavy attacks left.png",
    "Imagery/battle/Minotaur heavy attacks right.png",
    "Imagery/battle/Minotaur blocks left.png",
    "Imagery/battle/Minotaur blocks right.png",
    "Imagery/battle/Minotaur dead left.png",
    "Imagery/battle/Minotaur dead right.png",
    "Imagery/battle/Cyclops facing left.png",
    "Imagery/battle/Cyclops facing right.png",
    "Imagery/battle/Cyclops chasing left.png",
    "Imagery/battle/Cyclops chasing right.png",
    "Imagery/battle/Cyclops light attacks left.png",
    "Imagery/battle/Cyclops light attacks right.png",
    "Imagery/battle/Cyclops heavy attacks left.png",
    "Imagery/battle/Cyclops heavy attacks right.png",
    "Imagery/battle/Cyclops dead left.png",
    "Imagery/battle/Cyclops dead right.png",
    "Imagery/battle/Hades facing left.png",
    "Imagery/battle/Hades facing right.png",
    "Imagery/battle/Hades chasing left.png",
    "Imagery/battle/Hades chasing right.png",
    "Imagery/battle/Hades light attacks left.png",
    "Imagery/battle/Hades light attacks right.png",
    "Imagery/battle/Hades heavy attacks left.png",
    "Imagery/battle/Hades heavy attacks right.png",
    "Imagery/battle/Hades takes soul left.png",
    "Imagery/battle/Hades takes soul right.png",
    "Imagery/battle/Hades summons left.png",
    "Imagery/battle/Hades summons right.png",
    "Imagery/battle/Underground hand.png",
    "Imagery/battle/Hades dead left.png",
    "Imagery/battle/Hades dead right.png",
    // --- Olympus ----
    // Backgrounds
    "Imagery/battle/Hermes battle area.png",
    "Imagery/battle/Hercules battle area.png",
    "Imagery/battle/Zeus battle area.png",
    "Imagery/battle/Olympus battle area.png",
    // Enemies
    "Imagery/battle/Hermes facing left.png",
    "Imagery/battle/Hermes facing right.png",
    "Imagery/battle/Hermes chasing left.png",
    "Imagery/battle/Hermes chasing right.png",
    "Imagery/battle/Hermes light attacks left.png",
    "Imagery/battle/Hermes light attacks right.png",
    "Imagery/battle/Hermes heavy attacks left.png",
    "Imagery/battle/Hermes heavy attacks right.png",
    "Imagery/battle/Hermes dodges left.png",
    "Imagery/battle/Hermes dodges right.png",
    "Imagery/battle/Hermes sprints left.png",
    "Imagery/battle/Hermes sprints right.png",
    "Imagery/battle/Hermes dead left.png",
    "Imagery/battle/Hermes dead right.png",
    "Imagery/battle/Hercules facing left.png",
    "Imagery/battle/Hercules facing right.png",
    "Imagery/battle/Hercules chasing left.png",
    "Imagery/battle/Hercules chasing right.png",
    "Imagery/battle/Hercules light attacks left.png",
    "Imagery/battle/Hercules light attacks right.png",
    "Imagery/battle/Hercules heavy attacks left.png",
    "Imagery/battle/Hercules heavy attacks right.png",
    "Imagery/battle/Hercules blocks left.png",
    "Imagery/battle/Hercules blocks right.png",
    "Imagery/battle/Hercules smashes left.png",
    "Imagery/battle/Hercules smashes right.png",
    "Imagery/battle/Hercules dead left.png",
    "Imagery/battle/Hercules dead right.png",
    "Imagery/battle/Zeus facing left.png",
    "Imagery/battle/Zeus facing right.png",
    "Imagery/battle/Zeus chasing left.png",
    "Imagery/battle/Zeus chasing right.png",
    "Imagery/battle/Zeus light attacks left.png",
    "Imagery/battle/Zeus light attacks right.png",
    "Imagery/battle/Zeus heavy attacks left.png",
    "Imagery/battle/Zeus heavy attacks right.png",
    "Imagery/battle/Zeus teleports left.png",
    "Imagery/battle/Zeus teleports right.png",
    "Imagery/battle/Zeus blocks left.png",
    "Imagery/battle/Zeus blocks right.png",
    "Imagery/battle/Zeus levitates right.png",
    "Imagery/battle/Zeus levitates left.png",
    "Imagery/battle/Zeus flies right.png",
    "Imagery/battle/Zeus flies left.png",
    "Imagery/battle/Lightning bolt.png",
    "Imagery/battle/Zeus falls left.png",
    "Imagery/battle/Zeus falls right.png",
    "Imagery/battle/Zeus victory pose left.png",
    "Imagery/battle/Zeus victory pose right.png",
    "Imagery/battle/Zeus dead left.png",
    "Imagery/battle/Zeus dead right.png",
];

console.log("UI images:", UIassets.length);
console.log("Battle images:", battleAssets.length);

export const bAssets = new Map();

export default function loader(g, loadE, scene) {
    loadE.style.display = "flex";
    scene.style.display = "none";
    preloadImages(UIassets).then(() => {
        g.audio.mainTheme.play();
        loadE.style.display = "none";
        scene.style.display = "block";
        preloadImages(battleAssets).then(() => {
            console.log("Done");
        });
    });

    function preloadImages(srcs = []) {
        const progress = document.getElementById('progress');
        if (srcs.length === battleAssets.length) console.log("Downloading battle images in the background...");
        let loaded = 0;

        return new Promise(resolve => {
            if (srcs.length === 0) resolve();

            srcs.forEach(src => {
                const img = new Image();
                
                img.onload = img.onerror = async () => {
                    await img.decode();
                    loaded++;
                    srcs.length === UIassets.length ? progress.innerText = `${Math.round(loaded / srcs.length * 100)}%` : console.log(`Download progress: ${Math.round(loaded / srcs.length * 100)}%`);

                    if (loaded === srcs.length) resolve();
                };
                img.src = src;

                if (srcs.length === battleAssets.length) {
                    bAssets.set(src, img)
                } else { g.loaded = true }
            });
        });
    }
}
