const UIassets = [
    // Main menu
    "./Imagery/UI/Game start.gif",
    "./Imagery/UI/Opening menu image.png",
    // Stats
    "./Imagery/UI/Stats blade.png",
    "./Imagery/UI/Red orb.png",
    // Sparta
    "./Imagery/UI/Sparta.png",
    "./Imagery/UI/Kratos standing animation.gif",
    "./Imagery/UI/Sparta smithy.png",
    "./Imagery/UI/Underworld.png",
    "./Imagery/UI/Mount Olympus.png",
    // Smithy
    "./Imagery/UI/In smithy.png",
    "./Imagery/UI/Sparta background.jpg",
    "./Imagery/UI/Nemesis whip.png",
    "./Imagery/UI/Nemesis whip (outlined).png",
    "./Imagery/UI/Claws of Hades.png",
    "./Imagery/UI/Claws of Hades (outlined).png",
    "./Imagery/UI/Gauntlet of Zeus.png",
    "./Imagery/UI/Gauntlet of Zeus (outlined).png",
    "./Imagery/UI/Nemean cestus.png",
    "./Imagery/UI/Nemean cestus (outlined).png",
    "./Imagery/UI/Blade of Olympus.png",
    "./Imagery/UI/Blade of Olympus (outlined).png",
    // Underworld
    "./Imagery/UI/In underworld.png",
    "./Imagery/UI/Hoplite.png",
    "./Imagery/UI/Banshee.png",
    "./Imagery/UI/Satyr.png",
    "./Imagery/UI/Gorgon.png",
    "./Imagery/UI/Minotaur.png",
    "./Imagery/UI/Medusa.png",
    "./Imagery/UI/Cyclops.png",
    "./Imagery/UI/Hades.png",
    // Olympus
    "./Imagery/UI/Olympus background.png",
    "./Imagery/UI/Hermes.png",
    "./Imagery/UI/Hercules.png",
    "./Imagery/UI/Zeus.png"
];

const battleAssets = [
    // --- Kratos ---
    "Imagery/battle/Kratos dodging right.png",
    "Imagery/battle/Kratos dodging left.png",
    "Imagery/battle/Kratos fighting stance right (Blades of chaos).png",
    "Imagery/battle/Kratos fighting stance left (Blades of chaos).png",
    "Imagery/battle/Kratos fighting stance right (Blades of chaos)-lit.png",
    "Imagery/battle/Kratos fighting stance left (Blades of chaos)-lit.png",
    "Imagery/battle/Kratos light attacks right with blades of chaos 1.png",
    "Imagery/battle/Kratos light attacks right with blades of chaos 2.png",
    "Imagery/battle/Kratos light attacks right with blades of chaos 3.png",
    "Imagery/battle/Kratos light attacks left with blades of chaos 1.png",
    "Imagery/battle/Kratos light attacks left with blades of chaos 2.png",
    "Imagery/battle/Kratos light attacks left with blades of chaos 3.png",
    "Imagery/battle/Kratos heavy attacks right with blades of chaos 1.png",
    "Imagery/battle/Kratos heavy attacks right with blades of chaos 2.png",
    "Imagery/battle/Kratos heavy attacks left with blades of chaos 1.png",
    "Imagery/battle/Kratos heavy attacks left with blades of chaos 2.png",
    "Imagery/battle/Kratos blocking right with blades of chaos.png",
    "Imagery/battle/Kratos blocking left with blades of chaos.png",
    "Imagery/battle/Kratos aerial attack right with blades of chaos.png",
    "Imagery/battle/Kratos aerial attack left with blades of chaos.png",
    "Imagery/battle/Kratos fighting stance right (Nemesis whip).png",
    "Imagery/battle/Kratos fighting stance left (Nemesis whip).png",
    "Imagery/battle/Kratos fighting stance right (Nemesis whip)-lit.png",
    "Imagery/battle/Kratos fighting stance left (Nemesis whip)-lit.png",
    "Imagery/battle/Kratos light attacks right with nemesis whip 1.png",
    "Imagery/battle/Kratos light attacks right with nemesis whip 2.png",
    "Imagery/battle/Kratos light attacks right with nemesis whip 3.png",
    "Imagery/battle/Kratos light attacks left with nemesis whip 1.png",
    "Imagery/battle/Kratos light attacks left with nemesis whip 2.png",
    "Imagery/battle/Kratos light attacks left with nemesis whip 3.png",
    "Imagery/battle/Kratos heavy attacks right with nemesis whip 1.png",
    "Imagery/battle/Kratos heavy attacks right with nemesis whip 2.png",
    "Imagery/battle/Kratos heavy attacks left with nemesis whip 1.png",
    "Imagery/battle/Kratos heavy attacks left with nemesis whip 2.png",
    "Imagery/battle/Kratos blocking right with nemesis whip.png",
    "Imagery/battle/Kratos blocking left with nemesis whip.png",
    "Imagery/battle/Kratos aerial attack right with nemesis whip.png",
    "Imagery/battle/Kratos aerial attack left with nemesis whip.png",
    "Imagery/battle/Kratos fighting stance right (Claws of Hades).png",
    "Imagery/battle/Kratos fighting stance left (Claws of Hades).png",
    "Imagery/battle/Kratos fighting stance right (Claws of Hades)-lit.png",
    "Imagery/battle/Kratos fighting stance left (Claws of Hades)-lit.png",
    "Imagery/battle/Kratos light attacks right with claws of hades 1.png",
    "Imagery/battle/Kratos light attacks right with claws of hades 2.png",
    "Imagery/battle/Kratos light attacks right with claws of hades 3.png",
    "Imagery/battle/Kratos light attacks left with claws of hades 1.png",
    "Imagery/battle/Kratos light attacks left with claws of hades 2.png",
    "Imagery/battle/Kratos light attacks left with claws of hades 3.png",
    "Imagery/battle/Kratos heavy attacks right with claws of hades 1.png",
    "Imagery/battle/Kratos heavy attacks right with claws of hades 2.png",
    "Imagery/battle/Kratos heavy attacks left with claws of hades 1.png",
    "Imagery/battle/Kratos heavy attacks left with claws of hades 2.png",
    "Imagery/battle/Kratos blocking right with claws of hades.png",
    "Imagery/battle/Kratos blocking left with claws of hades.png",
    "Imagery/battle/Kratos aerial attack right with claws of hades.png",
    "Imagery/battle/Kratos aerial attack left with claws of hades.png",
    "Imagery/battle/Kratos fighting stance right (Gauntlet of Zeus).png",
    "Imagery/battle/Kratos fighting stance left (Gauntlet of Zeus).png",
    "Imagery/battle/Kratos light attacks right with gauntlet of zeus 1.png",
    "Imagery/battle/Kratos light attacks right with gauntlet of zeus 2.png",
    "Imagery/battle/Kratos light attacks left with gauntlet of zeus 1.png",
    "Imagery/battle/Kratos light attacks left with gauntlet of zeus 2.png",
    "Imagery/battle/Kratos heavy attacks right with gauntlet of zeus 1.png",
    "Imagery/battle/Kratos heavy attacks right with gauntlet of zeus 2.png",
    "Imagery/battle/Kratos heavy attacks left with gauntlet of zeus 1.png",
    "Imagery/battle/Kratos heavy attacks left with gauntlet of zeus 2.png",
    "Imagery/battle/Kratos blocking right with gauntlet of zeus.png",
    "Imagery/battle/Kratos blocking left with gauntlet of zeus.png",
    "Imagery/battle/Kratos aerial attack right with gauntlet of zeus.png",
    "Imagery/battle/Kratos aerial attack left with gauntlet of zeus.png",
    "Imagery/battle/Kratos fighting stance right (Nemean cestus).png",
    "Imagery/battle/Kratos fighting stance left (Nemean cestus).png",
    "Imagery/battle/Kratos light attacks right with nemean cestus 1.png",
    "Imagery/battle/Kratos light attacks right with nemean cestus 2.png",
    "Imagery/battle/Kratos light attacks left with nemean cestus 1.png",
    "Imagery/battle/Kratos light attacks left with nemean cestus 2.png",
    "Imagery/battle/Kratos heavy attacks right with nemean cestus 1.png",
    "Imagery/battle/Kratos heavy attacks right with nemean cestus 2.png",
    "Imagery/battle/Kratos heavy attacks left with nemean cestus 1.png",
    "Imagery/battle/Kratos heavy attacks left with nemean cestus 2.png",
    "Imagery/battle/Kratos blocking right with nemean cestus.png",
    "Imagery/battle/Kratos blocking left with nemean cestus.png",
    "Imagery/battle/Kratos aerial attack right with nemean cestus.png",
    "Imagery/battle/Kratos aerial attack left with nemean cestus.png",
    "Imagery/battle/Kratos fighting stance right (Blade of Olympus).png",
    "Imagery/battle/Kratos fighting stance left (Blade of Olympus).png",
    "Imagery/battle/Kratos fighting stance right (Blade of Olympus)-lit.png",
    "Imagery/battle/Kratos fighting stance left (Blade of Olympus)-lit.png",
    "Imagery/battle/Kratos light attacks right with blade of olympus 1.png",
    "Imagery/battle/Kratos light attacks right with blade of olympus 2.png",
    "Imagery/battle/Kratos light attacks left with blade of olympus 1.png",
    "Imagery/battle/Kratos light attacks left with blade of olympus 2.png",
    "Imagery/battle/Kratos heavy attacks right with blade of olympus 1.png",
    "Imagery/battle/Kratos heavy attacks right with blade of olympus 2.png",
    "Imagery/battle/Kratos heavy attacks left with blade of olympus 1.png",
    "Imagery/battle/Kratos heavy attacks left with blade of olympus 2.png",
    "Imagery/battle/Kratos blocking right with blade of olympus.png",
    "Imagery/battle/Kratos blocking left with blade of olympus.png",
    "Imagery/battle/Kratos aerial attack right with blade of olympus.png",
    "Imagery/battle/Kratos aerial attack left with blade of olympus.png",
    "Imagery/battle/Kratos damage right.png",
    "Imagery/battle/Kratos damage left.png",
    "Imagery/battle/Kratos air damage right.png",
    "Imagery/battle/Kratos air damage left.png",
    "Imagery/battle/Kratos petrified right.png",
    "Imagery/battle/Kratos petrified left.png",
    "Imagery/battle/Kratos held by hands right.png",
    "Imagery/battle/Kratos held by hands left.png",
    "Imagery/battle/Kratos dead right.png",
    "Imagery/battle/Kratos dead left.png",
    "Imagery/battle/Kratos dead as stone right.png",
    "Imagery/battle/Kratos dead as stone left.png",
    // --- Death screen image ---
    "Imagery/battle/You are dead GoW CoO.png",
    // --- Underworld ---
    // Backgrounds
    "Imagery/battle/Underworld battle area.png",
    "Imagery/battle/Hades battle area.png",
    // Enemies
    "Imagery/battle/Hoplite facing left.png",
    "Imagery/battle/Hoplite facing right.png",
    "Imagery/battle/Hoplite chasing left.png",
    "Imagery/battle/Hoplite chasing right.png",
    "Imagery/battle/Hoplite light attacks left.png",
    "Imagery/battle/Hoplite light attacks right.png",
    "Imagery/battle/Hoplite heavy attacks left.png",
    "Imagery/battle/Hoplite heavy attacks right.png",
    "Imagery/battle/Hoplite blocks left.png",
    "Imagery/battle/Hoplite blocks right.png",
    "Imagery/battle/Hoplite dead left.png",
    "Imagery/battle/Hoplite dead right.png",
    "Imagery/battle/Banshee facing left.png",
    "Imagery/battle/Banshee facing right.png",
    "Imagery/battle/Banshee chasing left.png",
    "Imagery/battle/Banshee chasing right.png",
    "Imagery/battle/Banshee light attacks left.png",
    "Imagery/battle/Banshee light attacks right.png",
    "Imagery/battle/Banshee heavy attacks left.png",
    "Imagery/battle/Banshee heavy attacks right.png",
    "Imagery/battle/Banshee screams left.png",
    "Imagery/battle/Banshee screams right.png",
    "Imagery/battle/Banshee dead left.png",
    "Imagery/battle/Banshee dead right.png",
    "Imagery/battle/Satyr facing left.png",
    "Imagery/battle/Satyr facing right.png",
    "Imagery/battle/Satyr chasing left.png",
    "Imagery/battle/Satyr chasing right.png",
    "Imagery/battle/Satyr light attacks left.png",
    "Imagery/battle/Satyr light attacks right.png",
    "Imagery/battle/Satyr heavy attacks left.png",
    "Imagery/battle/Satyr heavy attacks right.png",
    "Imagery/battle/Satyr blocks left.png",
    "Imagery/battle/Satyr blocks right.png",
    "Imagery/battle/Satyr dead left.png",
    "Imagery/battle/Satyr dead right.png",
    "Imagery/battle/Gorgon facing left.png",
    "Imagery/battle/Gorgon facing right.png",
    "Imagery/battle/Gorgon chasing left.png",
    "Imagery/battle/Gorgon chasing right.png",
    "Imagery/battle/Gorgon light attacks left.png",
    "Imagery/battle/Gorgon light attacks right.png",
    "Imagery/battle/Gorgon heavy attacks left.png",
    "Imagery/battle/Gorgon heavy attacks right.png",
    "Imagery/battle/Gorgon petrifies left.png",
    "Imagery/battle/Gorgon petrifies right.png",
    "Imagery/battle/Gorgon dead left.png",
    "Imagery/battle/Gorgon dead right.png",
    "Imagery/battle/Minotaur facing left.png",
    "Imagery/battle/Minotaur facing right.png",
    "Imagery/battle/Minotaur chasing left.png",
    "Imagery/battle/Minotaur chasing right.png",
    "Imagery/battle/Minotaur light attacks left.png",
    "Imagery/battle/Minotaur light attacks right.png",
    "Imagery/battle/Minotaur heavy attacks left.png",
    "Imagery/battle/Minotaur heavy attacks right.png",
    "Imagery/battle/Minotaur blocks left.png",
    "Imagery/battle/Minotaur blocks right.png",
    "Imagery/battle/Minotaur dead left.png",
    "Imagery/battle/Minotaur dead right.png",
    "Imagery/battle/Medusa facing left.png",
    "Imagery/battle/Medusa facing right.png",
    "Imagery/battle/Medusa chasing left.png",
    "Imagery/battle/Medusa chasing right.png",
    "Imagery/battle/Medusa light attacks left.png",
    "Imagery/battle/Medusa light attacks right.png",
    "Imagery/battle/Medusa heavy attacks left.png",
    "Imagery/battle/Medusa heavy attacks right.png",
    "Imagery/battle/Medusa petrifies left.png",
    "Imagery/battle/Medusa petrifies right.png",
    "Imagery/battle/Medusa dead left.png",
    "Imagery/battle/Medusa dead right.png",
    "Imagery/battle/Cyclops facing left.png",
    "Imagery/battle/Cyclops facing right.png",
    "Imagery/battle/Cyclops chasing left.png",
    "Imagery/battle/Cyclops chasing right.png",
    "Imagery/battle/Cyclops light attacks left.png",
    "Imagery/battle/Cyclops light attacks right.png",
    "Imagery/battle/Cyclops heavy attacks left.png",
    "Imagery/battle/Cyclops heavy attacks right.png",
    "Imagery/battle/Cyclops dead left.png",
    "Imagery/battle/Cyclops dead right.png",
    "Imagery/battle/Hades facing left.png",
    "Imagery/battle/Hades facing right.png",
    "Imagery/battle/Hades chasing left.png",
    "Imagery/battle/Hades chasing right.png",
    "Imagery/battle/Hades light attacks left.png",
    "Imagery/battle/Hades light attacks right.png",
    "Imagery/battle/Hades heavy attacks left.png",
    "Imagery/battle/Hades heavy attacks right.png",
    "Imagery/battle/Hades takes soul left.png",
    "Imagery/battle/Hades takes soul right.png",
    "Imagery/battle/Hades summons left.png",
    "Imagery/battle/Hades summons right.png",
    "Imagery/battle/Hades dead left.png",
    "Imagery/battle/Hades dead right.png",
    // --- Olympus ----
    // Backgrounds
    "Imagery/battle/Olympus battle area.png",
    "Imagery/battle/Zeus battle area.png",
    // Enemies
    "Imagery/battle/Hermes facing left.png",
    "Imagery/battle/Hermes facing right.png",
    "Imagery/battle/Hermes chasing left.png",
    "Imagery/battle/Hermes chasing right.png",
    "Imagery/battle/Hermes light attacks left.png",
    "Imagery/battle/Hermes light attacks right.png",
    "Imagery/battle/Hermes heavy attacks left.png",
    "Imagery/battle/Hermes heavy attacks right.png",
    "Imagery/battle/Hermes dodges left.png",
    "Imagery/battle/Hermes dodges right.png",
    "Imagery/battle/Hermes sprints left.png",
    "Imagery/battle/Hermes sprints right.png",
    "Imagery/battle/Hermes dead left.png",
    "Imagery/battle/Hermes dead right.png",
    "Imagery/battle/Hercules facing left.png",
    "Imagery/battle/Hercules facing right.png",
    "Imagery/battle/Hercules chasing left.png",
    "Imagery/battle/Hercules chasing right.png",
    "Imagery/battle/Hercules light attacks left.png",
    "Imagery/battle/Hercules light attacks right.png",
    "Imagery/battle/Hercules heavy attacks left.png",
    "Imagery/battle/Hercules heavy attacks right.png",
    "Imagery/battle/Hercules blocks left.png",
    "Imagery/battle/Hercules blocks right.png",
    "Imagery/battle/Hercules smashes left.png",
    "Imagery/battle/Hercules smashes right.png",
    "Imagery/battle/Hercules dead left.png",
    "Imagery/battle/Hercules dead right.png",
    "Imagery/battle/Zeus facing left.png",
    "Imagery/battle/Zeus facing right.png",
    "Imagery/battle/Zeus chasing left.png",
    "Imagery/battle/Zeus chasing right.png",
    "Imagery/battle/Zeus light attacks left.png",
    "Imagery/battle/Zeus light attacks right.png",
    "Imagery/battle/Zeus heavy attacks left.png",
    "Imagery/battle/Zeus heavy attacks right.png",
    "Imagery/battle/Zeus teleports left.png",
    "Imagery/battle/Zeus teleports right.png",
    "Imagery/battle/Zeus blocks left.png",
    "Imagery/battle/Zeus blocks right.png",
    "Imagery/battle/Zeus falls left.png",
    "Imagery/battle/Zeus falls right.png",
    "Imagery/battle/Zeus victory pose left.png",
    "Imagery/battle/Zeus victory pose right.png",
    "Imagery/battle/Zeus dead left.png",
    "Imagery/battle/Zeus dead right.png",
];

export default function loader(g, loadE, scene) {
    const lastCache = Number(localStorage.getItem("lastCache"));
    const nextCache = Number(localStorage.getItem("nextCache"));
    const twoWeeks = 1209600000;
    if (lastCache && nextCache) {
        console.log("Last cache:", new Date(lastCache));
        console.log("Next cache:", new Date(nextCache));
    }

    if (!nextCache || Date.now() > nextCache) {
        loadE.style.display = "flex";
        scene.style.display = "none";
        preloadImages(UIassets).then(() => {
            g.audios.mainTheme.play();
            loadE.style.display = "none";
            scene.style.display = "block";
            preloadImages(battleAssets).then(() => {
                localStorage.setItem("lastCache", Date.now());
                localStorage.setItem("nextCache", Date.now() + twoWeeks);
                console.log("Done");
            });
        });
    }

    function preloadImages(images = []) {
        const progress = document.getElementById('progress');
        if (images.length > 100) console.log("Downloading other images in the background...");
        let loaded = 0;

        return new Promise(resolve => {
            if (images.length === 0) resolve();

            images.forEach(src => {
                const img = new Image();
                
                img.onload = img.onerror = async () => {
                    await img.decode();
                    loaded++;
                    images.length <= 100 ? progress.innerText = `${Math.round(loaded / images.length * 100)}%` : console.log(`Download progress: ${Math.round(loaded / images.length * 100)}$`);

                    if (loaded === images.length) resolve();
                };
                img.src = src;
            });
        });
    }
}