export const audios = {
    mainTheme: new Audio('../Audio/Main menu theme GoW 3.mp3'),
    hoverSound: new Audio('../Audio/Hover sound GoW2.mp3'),
    hoverSound2: new Audio('../Audio/GoW CoO hover sound.mp3'),
    selection: new Audio('../Audio/GoW CoO Selection sound.mp3'),
    selection2: new Audio('../Audio/Other selection sound GoW2.mp3'),
    returnSound: new Audio('../Audio/GoW CoO Exit sound.mp3'),
    gameStart: new Audio('../Audio/Game start.mp3'),
    swordThud: new Audio('../Audio/Sword thud.mp3'),
    hmmmm: new Audio('../Audio/Hmm hmm Mc villager.mp3'),
    noice: new Audio('../Audio/Noice.mp3'),
    bruh: new Audio('../Audio/Bruh.mp3'),
    bocSound: new Audio('../Audio/Blades of chaos sound.mp3'),
    gozSound: new Audio('../Audio/Gauntlet of Zeus sound.mp3'),
    nwSound: new Audio('../Audio/Nemesis whip sound.mp3'),
    cohSound: new Audio('../Audio/Claws of Hades sound.mp3'),
    ncSound: new Audio('../Audio/Nemean cestus sound.mp3'),
    brokie: new Audio('../Audio/YOURE BROKE!.mp3'),
    battleTheme: new Audio('../Audio/GoW CoO battle theme.mp3'),
    battleTheme2: new Audio('../Audio/GoW CoO battle theme 2.mp3'),
    cyclopsBattle: new Audio('../Audio/Cyclops battle theme.mp3'),
    zeusBattle: new Audio('../Audio/Battle theme Zeus.mp3'),
    underworldAm: new Audio('../Audio/Underworld ambience.mp3'),
    hopliteSound: new Audio('../Audio/Hoplite sound.mp3'),
    hopliteAttacks: new Audio('../Audio/Hoplite attacks.mp3'),
    attacksHoplite: new Audio('../Audio/Kratos attacks Hoplite.mp3'),
    bansheeSound: new Audio('../Audio/Banshee sound.mp3'),
    bansheeAttacks: new Audio('../Audio/Banshee attacks.mp3'),
    bansheeAttacks2: new Audio('../Audio/Banshee attacks 2.mp3'),
    attacksBanshee: new Audio('../Audio/Kratos attacks Banshee.mp3'),
    satyrSound: new Audio('../Audio/Satyr sound.mp3'),
    satyrAttacks: new Audio('../Audio/Satyr attacks.mp3'),
    throwsSatyr: new Audio('../Audio/Kratos throws Satyr.mp3'),
    attacksSatyr: new Audio('../Audio/Kratos attacks Satyr.mp3'),
    minotaurSound: new Audio('../Audio/Minotaur sound.mp3'),
    minotaurAttacks: new Audio('../Audio/Minotaur attacks.mp3'),
    minotaurAttacks2: new Audio('../Audio/Minotaur attacks 2.mp3'),
    attacksMinotaur: new Audio('../Audio/Kratos attacks Minotaur.mp3'),
    medusaSound: new Audio('../Audio/Medusa snakes hiss.mp3'),
    medusaAttacks: new Audio('../Audio/Medusa attacks Kratos.mp3'),
    attacksMedusa: new Audio('../Audio/Kratos attacks Medusa.mp3'),
    olympusAm: new Audio('../Audio/Olympus ambience.mp3'),
    cyclopsSound: new Audio('../Audio/Cyclops sound.mp3'),
    cyclopsAttacks: new Audio('../Audio/Cyclops attacks.mp3'),
    cyclopsAttacks2: new Audio('../Audio/Cyclops attacks 2.mp3'),
    attacksCyclops: new Audio('../Audio/Kratos attacks Cyclops.mp3'),
    blockSound: new Audio('../Audio/Sword block sound.mp3'),
    hermesLine: new Audio('../Audio/You may have brute force.. but you lack speed.mp3'),
    hermesAttacks: new Audio('../Audio/Hermes attacks Kratos.mp3'),
    hermesAttacks2: new Audio('../Audio/Hermes attacks Kratos 2.mp3'),
    herculesLine: new Audio('../Audio/Hello.. brother.mp3'),
    herculesAttacks: new Audio('../Audio/Hercules attacks Kratos.mp3'),
    herculesAttacks2: new Audio('../Audio/Hercules attacks Kratos 2.mp3'),
    zeusLine: new Audio('../Audio/Such chaos... I will have much to do after I kill you.mp3'),
    zeusAttacks: new Audio('../Audio/Zeus attacks Kratos.mp3'),
    attacksZeus: new Audio('../Audio/Kratos attacks Zeus.mp3'),
    attacks: new Audio('../Audio/Kratos attacks.mp3'),
    attacks2: new Audio('../Audio/Kratos attacks 2.mp3'),
    evadeSound: new Audio('../Audio/Evade sound.mp3'),
    achievement: new Audio('../Audio/Achievment sound.mp3'),
    defeatSound: new Audio('../Audio/Defeat sound.mp3'),
    orbSound: new Audio('../Audio/Orb collection sound.mp3'),
    orbsSound: new Audio('../Audio/Orbs collection sound.mp3'),
    orbsSound2: new Audio('../Audio/Orbs collection sound 2.mp3'),
    orbsSound3: new Audio('../Audio/Orbs collection sound 3.mp3'),
    wonned: new Audio('../Audio/Wonned.mp3'),
    heartbeat: new Audio('../Audio/Heartbeat.mp3'),
    deathSound: new Audio('../Audio/Kratos death sound GoW2 2.mp3'),
    deathScream: new Audio('../Audio/Kratos death sound GoW2.mp3'),
    deathScream2: new Audio('../Audio/Kratos death sound GoW2 2.mp3'),
    ahShit: new Audio('../Audio/Ah shit, here we go again.mp3'),
    drink: new Audio('../Audio/Drinking.mp3')
};
